-- Production Admin User Creation
-- This file has been deprecated for security reasons.
-- Hardcoded credentials pose a significant security risk.
-- 
-- SECURITY NOTICE: This file previously contained hardcoded credentials
-- which have been removed to prevent unauthorized access.
--
-- To create a production admin user, use environment variables:
-- 1. Set ADMIN_EMAIL and ADMIN_PASSWORD in your deployment environment
-- 2. The application will automatically create the admin user on startup
-- 3. See server/index.ts for the secure admin creation implementation
--
-- DO NOT add hardcoded passwords or hashes to this file.